### ISSUE TITLE
Add ApiController::getAdminUserId()

### ISSUE THREAD

**Issue by AndyM84** [zibings/zsf#21]
A common set of lines inside controller endpoints looks like this:

```php
$user   = $this->getUser();
$params = $request->getInput();
$userId = $params->getInt('userId', $user->id);

if ($userId !== $user->id && !(new UserRoles($this->db, $this->log))->userInRoleByName($user->id, RoleStrings::ADMINISTRATOR)) {
  $ret->setAsError("Unauthorized");

  return $ret;
}
```

It's done enough that clearly we should have a method that does this for you.  Open to better naming and other thoughts.

**Comment by mhykes** [comment]
First three lines are getting the id for the user accessing the endpoint.
If block is rejecting non-admins.

We often need the user id to provide context for later processing, but we don't always want to reject based on administrator privileges.   So, two steps: getCurrentUserId()?, allowOnly(roles)?   Or else one step as getAuthorizedUserId([roles])?

**Comment by AndyM84** [comment]
The scenarios for `getCurrentUserId()` and `allowOnly(roles)` are already accounted for with `ApiController::getUser()` and the role-based ACL options for endpoint registration.  This is very specifically for situations where it is acceptable for administrators to specify they want to see/change info on another user (and maybe an optional restriction for admins vs admins?):

```
https://url.com/api/1.1/Account      <- OK for users to get their own info OR for admins
https://url.com/api/1.1/Search/Users <- OK for anyone to get profile info, as it is cleaned by user pref
```

**Comment by mhykes** [comment]
Ok.  If there are already simple methods for the other scenarios, and it is only this case with self or admin that isn't already covered, then this makes sense to collapse to a single utility method as suggested.

**Comment by AndyM84** [comment]
Had a conversation w/ @ctd1500, what if we did something closer to this:

```php
$ret                      = $this->newResponse();
[$user, $params, $userId] = $this->getBasicParams($request);

if (!$this->isSelfOrAdmin($user, $userId)) {
  $ret->setAsError("Unauthorized");

  return $ret;
}
```
